server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/db2022?characterEncoding=UTF-8&useUnicode=true&useSSL=true&serverTimezone=UTC
    username: root
    password: '000000'
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  client:
    #表示是否将白己E册Eurekaserver默以为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信.息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    serviceUrl:
      #        defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    prefer-ip-address: true
    instance-id: payment8002
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.wangwx.springcloud.entity      #所有Entity.别名类所在包
